image: ccr.ccs.tencentyun.com/huzi/alpine-node:8

stages:
  - deploy

deploy:develop:
  stage: deploy
  script:
    - ls -al
    - rsync -r --delete-after --force --delay-updates -e 'ssh -o UserKnownHostsFile=/dev/null  -o StrictHostKeyChecking=no' ./ ${DEVELOP_HOST}:/srv/static/red-packet/
  only:
    - develop

deploy:test:
  stage: deploy
  script:
    - ls -al
    - rsync -r --delete-after --force --delay-updates -e 'ssh -o UserKnownHostsFile=/dev/null  -o StrictHostKeyChecking=no' ./ ${TEST_HOST}:/srv/static/red-packet/
  only:
    - release