image: ccr.ccs.tencentyun.com/huzi/alpine-node:8

variables:
  SSH_OPTS: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  RSYNC_OPTS: "-r --exclude=.git --delete-after --force --delay-updates"

stages:
  - build
  - deploy

.cache: &cache
  key: "${CI_PROJECT_PATH}-${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/

build:develop:
  stage: build
  cache:
      <<: *cache
  script:
    - yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
    - yarn config set registry https://registry.npm.taobao.org -g
    - yarn install
    - npm run build:develop
  artifacts:
    paths:
      - dist/
  only:
    - develop

build:release:
  stage: build
  cache:
      <<: *cache
  script:
    - yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
    - yarn config set registry https://registry.npm.taobao.org -g
    - yarn install
    - npm run build:test
  artifacts:
    paths:
      - dist/
  only:
    - release

build:master:
  stage: build
  cache:
      <<: *cache
  script:
    - yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
    - yarn config set registry https://registry.npm.taobao.org -g
    - yarn install
    - npm run build:master
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy:develop:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - rsync $RSYNC_OPTS -e "ssh $SSH_OPTS" ./dist/ ${DEVELOP_HOST}:/srv/static/red-packet/
  only:
    - develop

deploy:release:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - rsync $RSYNC_OPTS -e "ssh $SSH_OPTS" ./dist/ ${TEST_HOST}:/srv/static/red-packet/
  only:
    - release
  when: manual

deploy:master:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - rsync $RSYNC_OPTS -e "ssh $SSH_OPTS" ./dist/ ${MASTER_HOST}:/srv/static/red-packet/
  only:
    - master
  when: manual